package api.redis;

public enum BroadcastType {

    CHAT,
    TITLE,
    ACTIONBAR,
    DISPATCH_COMMAND, 
    SUBTITLE,
    CHAT_ITEMSHOP_SPONSOR,
    CHAT_ITEMSHOP_VIP,
    CHAT_ITEMSHOP_SVIP,
    CHAT_ITEMSHOP_ZWYKLYKLUCZ,
    CHAT_ITEMSHOP_RZADKIKLUCZ,
    CHAT_ITEMSHOP_EPICKIKLUCZ,

}
